### ISSUE TITLE
0.2.0 (rotating cube) task list

### ISSUE THREAD

**Issue by larsivsi** [larsivsi/project_peril#2]
Things to do for 0.2.0 (rotating cube).
Bump patch version for each fixed issue
- [x] Clean up and split load_image() into load_image() and create_texture()
- create_texture() should optionally take a vk::Buffer that (if supplied) will be used to fill the texture with values
- [x] Add optimize flag to create_buffer() that if set will cause the use of staging buffers for optimal (DEVICE_LOCAL) buffer layout.
- [x] Implement a main render pass, which output is used as the texture for the final pass
- This will require the Camera's VP matrix and stuff
- [x] Implement a cuboid draw object that is drawn in the main render pass.
- [x] Implement a light source and some shading (Phong, f.inst.) for the main render pass
- [x] Make cube spin (independent of frame rate, see main loop)

**Comment by larsivsi** [comment]
This is technically done, since we have a hardcoded lightsource.
